from typing import TypedDict, List, Annotated, Optional
from langgraph.graph.message import add_messages

class SceneData(TypedDict):
    scene_number: int
    scene_text: str                  # Raw scene description from story generator
    characters_present: List[str]    # Extracted character names for this scene
    image_prompts: List[str]         # Prompt 2, Section 2: Image prompts
    video_prompts: List[str]         # Prompt 2, Section 3: Video motion prompts
    optimized_video_prompts: List[str] # After camera move optimization
    generated_images: List[str]      # Local file paths to images
    generated_videos: List[str]      # Local file paths to videos
    approved: bool                   # Human-in-the-loop approval flag

class PipelineState(TypedDict):
    # User input
    movie_idea: str
    chat_id: int                     # Telegram chat ID for sending updates

    # Generated by Agent 1 (scene_generator)
    story_snapshot: str
    character_definitions: dict      # { name: description }
    scenes: List[SceneData]

    # Processing cursor/state
    current_scene_index: int

    # Human checkpoint flags
    scenes_approved: bool
    current_scene_approved: bool

    # LLM conversation history
    messages: Annotated[list, add_messages]
